name: spurs
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - nvidia
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - pytorch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - blas=1.0=mkl
  - brotli-python=1.1.0=py39hf88036b_3
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.17.1=py39h15c3d72_0
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - cpython=3.9.23=py39hd8ed1ab_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=13.1.115=h4f1e1d6_0
  - cuda-runtime=12.1.0=0
  - cuda-version=13.1=hd92462c_3
  - ffmpeg=4.4.0=hca11adc_2
  - filelock=3.19.1=pyhd8ed1ab_0
  - freetype=2.14.1=ha770c72_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py39h7196dd7_0
  - gnutls=3.6.13=h85f3911_1
  - h2=4.2.0=pyhd8ed1ab_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=78.1=h33c6efd_0
  - idna=3.10=pyhd8ed1ab_1
  - intel-openmp=2023.0.0=h9e868ea_25371
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jpeg=9e=h166bdaf_2
  - lame=3.100=h166bdaf_1003
  - lcms2=2.15=hfd0df8a_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_105
  - lerc=4.0.0=h0aef613_1
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libcblas=3.9.0=13_h8e06fc2_netlib
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.16.1.26=h3b4bcfc_0
  - libcurand=10.4.1.81=h1b6c897_0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.17=h0b41bf4_0
  - libexpat=2.7.3=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran-ng=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libgomp=15.2.0=he0feb66_16
  - libhwloc=2.12.2=default_hafda6a7_1000
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - liblapack=3.9.0=13_h8876d29_netlib
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnpp=12.0.2.50=0
  - libnsl=2.0.1=hb9d3cd8_1
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libpng=1.6.54=h421ea60_0
  - libsqlite=3.51.1=hf4e2dac_1
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libtiff=4.5.0=h6adf6a1_2
  - libuuid=2.41.3=h5347b49_0
  - libvpx=1.11.0=h9c3ff4c_3
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.13=h7f98852_1004
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.15.1=he237659_1
  - libxml2-16=2.15.1=hca6bf5a_1
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=15.0.7=h0cdce71_0
  - markupsafe=3.0.2=py39h9399b63_1
  - mkl=2023.1.0=h213fc3f_46344
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - nettle=3.6=he412f7d_0
  - networkx=3.2.1=pyhd8ed1ab_0
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.6.0=h26f9b46_0
  - pillow=9.4.0=py39h2320bf1_1
  - pip=24.0=pyhd8ed1ab_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pycparser=2.22=pyh29332c3_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.9.23=hc30ae73_0_cpython
  - python_abi=3.9=8_cp39
  - pytorch=2.1.2=py3.9_cuda12.1_cudnn8.9.2_0
  - pytorch-cuda=12.1=ha16c6d3_6
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.2=py39h9399b63_2
  - readline=8.3=h853b02a_0
  - requests=2.32.5=pyhd8ed1ab_0
  - setuptools=69.0.3=pyhd8ed1ab_0
  - sqlite=3.51.1=h04a0ce9_1
  - sympy=1.14.0=pyh2585a3b_105
  - tbb=2021.13.0=hb700be7_5
  - tk=8.6.13=noxft_ha0e22de_103
  - torchaudio=2.1.2=py39_cu121
  - torchtriton=2.1.0=py39
  - torchvision=0.16.2=py39_cu121
  - typing_extensions=4.14.1=pyhe01879c_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wheel=0.42.0=pyhd8ed1ab_0
  - x264=1!161.3030=h7f98852_1
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml=0.2.5=h280c20c_3
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.23.0=py39hd399759_3
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.1
      - argparse==1.4.0
      - asttokens==3.0.1
      - async-timeout==5.0.1
      - atom3d==0.2.6
      - attrs==25.4.0
      - biopython==1.85
      - blosc2==2.5.1
      - click==8.1.8
      - decorator==5.2.1
      - dill==0.4.0
      - easy-parallel==0.1.6
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - fair-esm==2.0.0
      - fairscale==0.4.13
      - freesasa==2.2.1
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - h11==0.16.0
      - h5py==3.14.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.3.2
      - hydra-core==1.3.2
      - ipython==8.18.1
      - jedi==0.19.2
      - joblib==1.5.3
      - lightning-utilities==0.15.2
      - lmdb==1.7.5
      - markdown-it-py==3.0.0
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - msgpack==1.1.2
      - multidict==6.7.0
      - multipledispatch==1.0.0
      - multiprocess==0.70.18
      - ndindex==1.10.1
      - numexpr==2.10.2
      - numpy==1.26.4
      - omegaconf==2.3.0
      - packaging==25.0
      - pandas==2.3.3
      - parso==0.8.5
      - pathos==0.3.4
      - pexpect==4.9.0
      - pox==0.3.6
      - ppft==1.7.7
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - psutil==7.2.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pygments==2.19.2
      - pyparsing==3.3.1
      - pyrr==0.10.3
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - pytorch-lightning==1.9.0
      - pytz==2025.2
      - rich==14.2.0
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - shellingham==1.5.4
      - six==1.17.0
      - stack-data==0.6.3
      - tables==3.9.2
      - threadpoolctl==3.6.0
      - torch-geometric==2.6.1
      - torchdata==0.7.1
      - torchmetrics==1.8.2
      - torchtext==0.16.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typer-slim==0.21.1
      - tzdata==2025.3
      - wcwidth==0.2.14
      - yarl==1.22.0
prefix: /home/adsb/conda/envs/spurs
